---

- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755

- name: Create K3S config directory
  file:
    path: "{{ k3s_config_dir }}"
    state: directory

- name: Copy K3s registries file
  template:
    src: "registries.yaml.j2"
    dest: "{{ k3s_config_dir }}/registries.yaml"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes
